{% set name = "apache-airflow-providers-apache-drill" %}
{% set version = "1.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/apache-airflow-providers-apache-drill-{{ version }}.tar.gz
  sha256: 44be18ba536f669071efa4f5ded2ba39e29ae78902b58f5e68ea5aa1e633a7bc

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - apache-airflow >=2.1.0
    - sqlalchemy-drill >=1.1.0
    - sqlparse >=0.4.1

test:
  imports:
    - airflow.providers.apache.drill
    - airflow.providers.apache.drill.example_dags
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://airflow.apache.org/
  summary: Provider for Apache Drill for Apache Airflow
  license: Apache-2.0
  license_file: LICENSE
  doc_url: https://airflow.apache.org/docs/apache-airflow-providers-apache-drill/stable/index.html
  dev_url: https://github.com/apache/airflow/
extra:
  recipe-maintainers:
    - xylar
