{% set name = "apache-airflow-providers-apache-drill" %}
{% set version = "2.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/apache_airflow_providers_apache_drill-{{ version }}.tar.gz
  sha256: fa552d82a5095bac085aee2e10713bb355ec45814774ff81e903b535e6d8cec3

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8,<4.dev0
    - flit-core >=3.2,<4
    - pip
  run:
    - python >=3.8,<4.dev0
    - apache-airflow-providers-common-sql >=1.14.1
    - apache-airflow >=2.8.0
    - sqlalchemy-drill >=1.1.0

test:
  imports:
    - airflow.providers.apache.drill
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/apache/airflow/
  summary: Provider package apache-airflow-providers-apache-drill for Apache Airflow
  license: Apache-2.0
  license_file: airflow/providers/apache/drill/LICENSE
  license_family: Apache
  doc_url: https://airflow.apache.org/docs/apache-airflow-providers-apache-drill/stable/index.html
  dev_url: https://github.com/apache/airflow/

extra:
  recipe-maintainers:
    - xylar
