context:
  name: apache-airflow-providers-apache-drill
  version: 3.3.0

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/apache_airflow_providers_apache_drill-${{ version }}.tar.gz
  sha256: 3cffeebf2b2fcb2e0e9f02e4c05694b3908c699c4ddb92752d6da4caca7a4fc8

build:
  noarch: python
  script: python -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - flit-core ==3.12.0
  run:
    - python >=${{ python_min }}
    - apache-airflow >=2.11.0
    - apache-airflow-providers-common-sql >=1.32.0
    - apache-airflow-providers-common-compat >=1.8.0
    - sqlalchemy-drill >=1.1.0,!=1.1.6,!=1.1.7
tests:
  - python:
      imports:
        - airflow.providers.apache.drill
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  homepage: https://github.com/apache/airflow/
  summary: Provider package apache-airflow-providers-apache-drill for Apache Airflow
  license: Apache-2.0
  license_file:
    - LICENSE
    - NOTICE
  documentation: https://airflow.apache.org/docs/apache-airflow-providers-apache-drill/stable/index.html
  repository: https://github.com/apache/airflow/

extra:
  recipe-maintainers:
    - xylar
